### PR TITLE
Add TS definitions

### LINKED ISSUE #84: TypeScript and dagrejs npm organization
I'm currently having issues with using the existing typescript bindings (https://www.npmjs.com/package/@types/graphlib) with the latest graphlib release (https://www.npmjs.com/package/@dagrejs/graphlib). Due to the organization switch I have to import it as 

```
import {Graph} from '@dagrejs/graphlib';
```

However, the Typescript bindings are defined for just the `graphlib` module namespace, thus not applying. In the best case the typings are directly integrated and provided as part of this library.

### PR DESCRIPTION
**Pull request by amaurym**
Copy-pasted the .d.ts file from @types/graphlib.

Closes #84

### CODE REVIEW

**Comment by lkostrowski** [comment]
Any progress here?

**Comment by amaurymartiny** [comment]
On my side?

**Comment by FunkMonkey** [comment]
I would be interested in this, too! I'd also propose to have an interface `IGraph` besides the class `Graph`.

Thanks!

**Comment by zmitry** [comment]
check this out for typings https://github.com/zmitry/graphlib
and also this one http://github.com/zmitry/struct/graph which uses a more modern way.

**Comment by FunkMonkey** [comment]
@amaurymartiny Since not much is happening here, do we want to update the typings at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/graphlib/). I like yours much better as they are generic!

**Comment by assafsun** [comment]
small question for my understanding, does this PR will deprecate the use of @types/graphlib as it will not be needed anymore?

**Comment by FunkMonkey** [comment]
@assafsun 

yes it will. TS types will be delivered with the npm module itself

**Comment by assafsun** [comment]
Thanks for the reply, I believe that that's the right step in order to prevent version conflicts and more unless I'm missing something.

I recommend of keeping the changes as it is and separate the changes to:
1. Move the type script definitions as they are and how this PR handle it.
2. Future PRs will improve it as was suggested here.

From what I noticed, there was no change from the current graphlib types file to this PR right? Making sure with you also because this is an old PR.

**Comment by FunkMonkey** [comment]
I'm not quite sure I understand your point 1. Move the definitions where?

I believe the current graphlib types (`@types/graphlib`) are from [DefinetelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/graphlib/index.d.ts). Unfortunately those are not templated but simply use `any` for edge and node types. The types from this PR by @amaurymartiny  are superior in this regard...

**Comment by assafsun** [comment]
My point is that this PR started with moving the type definition from @types/graphLib **as it is** and it seems like a good start that will help issue 84.
(Sorry, my mistake, I didn't noticed that the latest commit contains updates to the .d. file). 

Regrading the types improvement and remove the use of 'any', i'm not sure this is a change that should be inserted now especially where this project is less maintain.
IMO, this require testing and verification that it will not break any projects, especially where after this PR, we will have two different sources of definitions.

**Comment by FunkMonkey** [comment]
> IMO, this require testing and verification that it will not break any projects, especially when after this PR, we will have two different sources of definitions that may cause confusion.

The doubling of definitions will definitely lead to TS errors, as both definitions can't live side-by-side. Whoever gets the new version will be forced to remove `@types/graphlib` anyway.

> Regrading the types improvement and remove the use of 'any', i'm not sure this is a change that should be inserted now especially where this project is less maintain.

I strongly believe that the templated version should be used.

1. the use of any is completely discouraged in TypeScript
2. leaving them as `any` makes the types kinda pointless. Every call to get information out of the graph like `node('foo')` will return `any` and thus force the user to cast the value to the correct type.
3. don't just think of it as breaking projects, the templated versions may also show errors / wrong assumptions in existing projects
4. libraries have to evolve and none of these are really strong changes.
5. whoever really doesn't want to give types for nodes and edges, can still use `Graph` without types, as `any` is the default for the template params (or use `Graph<any, any>` directly). I assume most projects won't need any changes, but we should verify that

Do you have a list of projects that we could just test the new definitions against to see if problems arise?

Thanks!

**Comment by assafsun** [comment]
Thanks for the comments and fast reply.

No, I don't have a list of projects and we can't be really sure which projects are using it and how.

I think for now we can't make any progress with our discussion because this is a project which is less maintained so it's hard to take responsibility and give support for this change at this point.

**Comment by FunkMonkey** [comment]
@assafsun 

I understand, but I'm all in for a pragmatic solution, so this library can move forward. 

If you don't have much time, we obviously need to bring this into a format that only needs a very quick review on your side and convinces you that this PR will not have any negative consequences. As you can see in this PR @amaurymartiny and I are here to assist you your maintainment of this wonderful project.

I thus propose that I:
- create test files with every `graphlib` API call and test them against the old and the proposed types to see what differences there would be for people who upgrade.
-  verify the new types against the existing [dependents](https://www.npmjs.com/package/@types/graphlib) from npm

Would you need any other confirmations other than the results of my steps above?

Thanks a lot!

**Comment by assafsun** [comment]
Thank you @FunkMonkey, I highly appreciate your suggestion and reply.
I don't have anything new to add but it's important to me to reply in order not to leave our conversation open without a reply.

As mentioned in my message above, we can't progress our thread  because I'm not sure if there is an owner to this project (I'm not the owner). Please note that I'm sure you will do a good job with updating the TS files but it's not easy to take responsibility on it for the long term for all graphlib users (I also wanted to improve some items same as you).

My suggestion to you is to keep your required changes local at your repositories as I'm sure you are doing and as I will do.

You are welcome to update this PR and I will be happy to review it and test it in case someone will want to use it (just tag me).

Thanks!

**Comment by tuuling** [comment]
Would be nice to get this one!

**Comment by koxu1996** [comment]
Any ETA?

**Review by 9renpoto — APPROVED** [review]

**Comment by ingun37** [comment]
Any reason it’s not getting merged?

**Review by StephanGuingor — APPROVED** [review]

**Comment by rustedgrail** [comment]
Manually merged this PR. Thanks for the help!

**Pull request closed without merging**
